import test from 'node:test';import assert from 'node:assert/strict';
import {accountLegalAudience} from '../supabase/functions/_shared/legal-audience.mjs';
import {accountLegalLibrary} from '../supabase/functions/_shared/account-legal-library.mjs';
function service(){const docs=['BASIC','BASIC_REFERRAL','PREMIUM_EQUIPMENT','PREMIUM_BROKER'].map(a=>({id:a,audience:a,document_type:'PRICE_SHEET',title:a,version:1,status:'ACTIVE',effective_from:'2020-01-01',sandbox_onboarding_id:null,deletion_requested_at:null,storage_path:'private/'+a}));docs.push(...['TERMS','PRIVACY','CONDITIONS'].map(type=>({id:type,audience:'COMMON',document_type:type,title:type,version:1,status:'ACTIVE',effective_from:'2020-01-01',sandbox_onboarding_id:null,deletion_requested_at:null,storage_path:'private/'+type})));docs.push({id:'old',audience:'BASIC',status:'ARCHIVED',title:'Old own terms',version:1,storage_path:'private/old'});
 const data={partner_onboardings:[{id:'flow',auth_user_id:'me'}],legal_acceptances:[{onboarding_id:'flow',legal_document_id:'old',document_type:'TERMS',document_version:1,accepted_at:'2020-01-01'}],legal_documents:docs},signed=[];
 return {signed,from(table){let filters=[];const q={select(){return q},eq(k,v){filters.push(x=>x[k]===v);return q},is(k,v){return q.eq(k,v)},lte(k,v){filters.push(x=>x[k]<=v);return q},in(k,v){filters.push(x=>v.includes(x[k]));return q},order(){return q},then(resolve){return Promise.resolve({data:data[table].filter(x=>filters.every(f=>f(x)))}).then(resolve)}};return q},storage:{from(){return {createSignedUrl:async(path,ttl)=>{signed.push({path,ttl});return {data:{signedUrl:'https://example.test/signed'}}}}}}};
}
test('audience derives from plan and partner type, never ACL role alone',()=>{assert.equal(accountLegalAudience({plan:'basic',primaryTradeId:'BROKER'}),'BASIC');assert.equal(accountLegalAudience({plan:'premium',primaryTradeId:'BROKER'}),'PREMIUM_BROKER');assert.equal(accountLegalAudience({plan:'premium',partnerCategory:'broker'}),'PREMIUM_BROKER');assert.equal(accountLegalAudience({plan:'premium',role:'broker_partner'}),'PREMIUM_BROKER');assert.equal(accountLegalAudience({plan:'premium',primaryTradeId:'EQUIP_HEIZUNG'}),'PREMIUM_EQUIPMENT');assert.equal(accountLegalAudience({referralOnly:true,plan:'premium'}),'BASIC_REFERRAL');assert.equal(accountLegalAudience({}),null)});
test('Tippgeber cannot list or sign documents for another role',async()=>{const s=service(),partner={plan:'basic',referralOnly:true};const result=await accountLegalLibrary({service:s,actorId:'me',partner});assert.deepEqual(result.documents.map(d=>d.id),['BASIC_REFERRAL','TERMS','PRIVACY','CONDITIONS']);assert.deepEqual(result.historyDocuments.map(d=>d.id),['old']);for(const documentId of ['BASIC','PREMIUM_BROKER','PREMIUM_EQUIPMENT'])await assert.rejects(accountLegalLibrary({service:s,actorId:'me',partner,documentId}),e=>e.status===404);assert.equal(s.signed.length,0);assert.ok(!JSON.stringify(result).includes('private/'))});
test('upgrade changes current library, retains actual prior consent in separate archive',async()=>{const s=service(),partner={plan:'premium',primaryTradeId:'EQUIP_HEIZUNG'};const result=await accountLegalLibrary({service:s,actorId:'me',partner});assert.deepEqual(result.documents.map(d=>d.id),['PREMIUM_EQUIPMENT','TERMS','PRIVACY','CONDITIONS']);assert.equal(result.documents[0].acceptedAt,null);assert.equal(result.historyDocuments[0].id,'old');await accountLegalLibrary({service:s,actorId:'me',partner,documentId:'PREMIUM_EQUIPMENT'});assert.deepEqual(s.signed[0],{path:'private/PREMIUM_EQUIPMENT',ttl:60})});
test('legacy broker record without plan still receives broker documents',async()=>{const result=await accountLegalLibrary({service:service(),actorId:'me',partner:{partnerCategory:'Immobilienmakler'}});assert.equal(result.audience,'PREMIUM_BROKER');assert.deepEqual(result.documents.map(d=>d.id),['PREMIUM_BROKER','TERMS','PRIVACY','CONDITIONS'])});
