import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateRelevance, processTriggerEvent, suppressionReason } from '../lib/opportunity-engine.mjs';

const definition={id:'td-1',minimumRelevanceScore:60,cooldownDays:30,contactPeriodDays:30,maxCustomerContactsPerPeriod:2,requiredPropertyConditions:{requiresEquipment:true},relevantEquipmentTypes:['roof'],relevantTrades:['roof'],customerActionTemplateId:'cat-1',partnerActionType:'Dach',scoreRules:[{code:'severity',label:'Starkes Ereignis',path:'event.severity',operator:'gte',value:70,points:30},{code:'area',label:'Gebiet stimmt',path:'computed.locationMatched',operator:'eq',value:true,points:25},{code:'age',label:'Dachalter',path:'computed.equipmentAge',operator:'gt',value:25,points:15},{code:'health',label:'Kritischer Zustand',path:'health.score',operator:'lt',value:50,points:15},{code:'recent',label:'Kürzlich geprüft',path:'equipment.lastMaintenance',operator:'within_days',value:60,points:-40}]};
const context={now:'2026-08-21T12:00:00Z',event:{severity:85},computed:{locationMatched:true,equipmentAge:28},equipment:{lastMaintenance:'2023-01-01'},health:{score:40}};

test('Relevance Score ist regelbasiert und nachvollziehbar',()=>{const result=calculateRelevance(definition,context);assert.equal(result.scoreTotal,85);assert.equal(result.decision,'relevant');assert.deepEqual(result.breakdown.map(x=>x.code),['severity','area','age','health'])});
test('Kürzlich erfolgte Prüfung senkt Relevanz',()=>{const result=calculateRelevance(definition,{...context,equipment:{lastMaintenance:'2026-08-01'}});assert.equal(result.scoreTotal,45);assert.equal(result.decision,'rejected')});
test('Cooldown unterdrückt erneuten Kundenkontakt',()=>{const state={customerActions:[{propertyId:'p1',triggerDefinitionId:'td-1',triggerEventId:'old',status:'sent',createdAt:'2026-08-10'}],serviceCases:[]};assert.equal(suppressionReason(definition,{id:'new'},{id:'p1'},state,'2026-08-21'),'cooldown')});
test('Dasselbe Event erzeugt keine doppelte Kundenaktion',()=>{const state={customerActions:[{propertyId:'p1',triggerDefinitionId:'td-1',triggerEventId:'e1',status:'proposed',createdAt:'2026-08-21'}],serviceCases:[]};assert.equal(suppressionReason(definition,{id:'e1'},{id:'p1'},state,'2026-08-21'),'duplicate_event')});
test('Eventverarbeitung ist idempotent und Partner erhält aggregierte Opportunity',()=>{let n=0;const state={properties:[{id:'p1',customerId:'c1',postalCode:'22301'}],equipmentRecords:[{id:'eq1',propertyId:'p1',tradeId:'roof',year:1990,lastMaintenance:'2023-01-01'}],postalDirectory:[{postalCode:'22301',state:'Hamburg'},{postalCode:'22111',state:'Hamburg'}],partners:[{id:'partner1',status:'active',primaryTradeId:'roof',postalCodes:['22111']}],customerActions:[],serviceCases:[],affectedProperties:[],partnerOpportunities:[],opportunityEvents:[]},event={id:'e1',severity:85,postalCodes:['22301'],processingStatus:'queued'},args={definition,event,state,getHealth:()=>({score:40}),id:p=>`${p}-${++n}`,now:'2026-08-21T12:00:00Z'};const first=processTriggerEvent(args);assert.equal(first.opportunities.length,1);assert.equal(first.opportunities[0].propertyCount,1);assert.equal(state.customerActions.length,1);const second=processTriggerEvent(args);assert.equal(second.idempotent,true);assert.equal(state.customerActions.length,1)});
