import test from 'node:test';
import assert from 'node:assert/strict';
import { channelForKind, sendPortalMail, smtpConfiguration, supabaseMailConfiguration } from '../lib/smtp-mail.mjs';

test('Registrierung und Empfehlungen verwenden das Registrierungs-Postfach',()=>{assert.equal(channelForKind('referral.invitation'),'registration');assert.equal(channelForKind('partner_basic.confirmation'),'registration');assert.equal(channelForKind('auth.password_reset'),'registration')});
test('Allgemeine Partnerkommunikation verwendet das Partner-Postfach',()=>assert.equal(channelForKind('partner.general'),'partner'));
test('SMTP ist nur mit Host und passendem Secret aktiv',()=>{const config=smtpConfiguration('partner',{MAIL_TRANSPORT:'smtp',SMTP_HOST:'w001.kasserver.com',SMTP_PARTNER_USER:'partner@eigenheimverwalter.de',SMTP_PARTNER_PASSWORD:'secret'});assert.equal(config.configured,true);assert.equal(config.port,465);assert.equal(config.from,'partner@eigenheimverwalter.de')});
test('Technischer Kontoname und sichtbarer Absender bleiben getrennt',()=>{const config=smtpConfiguration('registration',{MAIL_TRANSPORT:'smtp',SMTP_HOST:'w01e0654.kasserver.com',SMTP_REGISTRATION_USER:'m0673807',SMTP_REGISTRATION_PASSWORD:'secret'});assert.equal(config.user,'m0673807');assert.equal(config.from,'registrierung@eigenheimverwalter.de')});
test('Öffentliche ALL-INKL-Verbindungsdaten benötigen nur noch das geheime Passwort',()=>{const config=smtpConfiguration('partner',{MAIL_TRANSPORT:'smtp',SMTP_PARTNER_PASSWORD:'secret'});assert.equal(config.host,'w01e0654.kasserver.com');assert.equal(config.user,'m07c73cd');assert.equal(config.configured,true)});
test('Versand übergibt niemals das andere Postfach an den Transport',async()=>{let captured;const delivery=await sendPortalMail({to:'kunde@example.test',subject:'Einladung',text:'Text',kind:'referral.invitation',env:{MAIL_TRANSPORT:'smtp',SMTP_HOST:'w001.kasserver.com',SMTP_REGISTRATION_PASSWORD:'secret'},transport:async(config,envelope)=>{captured={config,envelope};return{status:'sent'}}});assert.equal(delivery.status,'sent');assert.equal(captured.config.from,'registrierung@eigenheimverwalter.de');assert.equal(captured.envelope.to,'kunde@example.test')});
test('Supabase-Gateway benötigt einen langen serverseitigen Zugriffsschlüssel',()=>{assert.equal(supabaseMailConfiguration({MAIL_TRANSPORT:'supabase',SUPABASE_MAIL_GATEWAY_TOKEN:'zu-kurz'}).configured,false);assert.equal(supabaseMailConfiguration({MAIL_TRANSPORT:'supabase',SUPABASE_MAIL_GATEWAY_TOKEN:'x'.repeat(32)}).configured,true)});
test('Pilot versendet über Supabase per HTTPS und übermittelt kein SMTP-Passwort',async()=>{let request;const delivery=await sendPortalMail({to:'kunde@example.test',subject:'Einladung',text:'Hallo',channel:'registration',env:{MAIL_TRANSPORT:'supabase',SUPABASE_MAIL_GATEWAY_TOKEN:'x'.repeat(32)},fetchImpl:async(url,options)=>{request={url,options};return{ok:true,json:async()=>({status:'sent',sender:'registrierung@eigenheimverwalter.de',messageId:'mail-1',sentAt:'2026-08-31T12:00:00Z'})}}});const body=JSON.parse(request.options.body);assert.equal(request.url.startsWith('https://'),true);assert.equal(request.options.headers['x-pilot-mail-token'],'x'.repeat(32));assert.equal(body.channel,'registration');assert.equal(JSON.stringify(body).includes('PASSWORD'),false);assert.equal(delivery.status,'sent')});
