import { corsHeaders } from "../_shared/cors.ts";
import { array, clean, identifier, loadRuntime, serviceClient } from "../_shared/runtime.ts";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
const emailOk=(v:string)=>/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v)&&v.length<=254,passwordOk=(v:string)=>v.length>=12&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/\d/.test(v)&&/[!@#$%^&*]/.test(v);
const allowedOrigin=(req:Request)=>{const value=req.headers.get("Origin")||"";try{const u=new URL(value),h=u.hostname.toLowerCase();return u.protocol==="https:"&&(h.endsWith("eigenheimverwalter.de")||h.endsWith("eigenheimverwalter-pilot.de")||h.endsWith("eigenheimverkauf.com")||h.endsWith("github.io")||h.endsWith("onrender.com"))?u.origin:""}catch{return""}};
const sendMail=async(to:string,subject:string,message:string)=>{const token=Deno.env.get("PILOT_MAIL_GATEWAY_TOKEN")||"";if(token.length<48)throw new Error("Registrierungsversand nicht konfiguriert");const response=await fetch(`${Deno.env.get("SUPABASE_URL")}/functions/v1/portal-mail`,{method:"POST",headers:{"Content-Type":"application/json","x-pilot-mail-token":token},body:JSON.stringify({action:"pilot_send_email",channel:"registration",recipientEmail:to,subject,message})});if(!response.ok)throw new Error("Registrierungs-E-Mail konnte nicht versendet werden")};
const replace=async(service:ReturnType<typeof serviceClient>,snapshot:Awaited<ReturnType<typeof loadRuntime>>,action:string,type:string,id:string)=>{const {error}=await service.rpc("replace_portal_runtime_state",{expected_revision:snapshot.revision,next_payload:snapshot.state,audit_actor:null,audit_action:action,audit_entity_type:type,audit_entity_id:id,audit_metadata:{source:"portal-public"}});if(error)throw new Error(String(error.message).includes("runtime_revision_conflict")?"Daten wurden parallel geändert. Bitte erneut versuchen.":"Registrierung konnte nicht gespeichert werden")};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders});const path=new URL(req.url).pathname.replace(/^.*\/portal-public/,"")||"/",service=serviceClient();try{
  if(req.method==="GET"&&path==="/health")return json({service:"ehv-pilot-portal-public",projectRef:"rpniwtshbwjuesoeztyt",status:"ok"});
  if(req.method==="GET"&&path==="/partner-basic/trades"){const state=(await loadRuntime(service)).state;return json({trades:array(state.trades).filter(x=>x.onboarding!==false&&x.tier!=="legacy").map(({id,name,tier})=>({id,name,tier})),selection:"single"})}
  if(req.method==="POST"&&path==="/partner-basic/register"){const b=await req.json(),email=clean(b.email,254).toLowerCase(),password=String(b.password||""),name=clean(b.name,120),company=clean(b.company,160)||name,address=clean(b.address,180),postalCode=String(b.postalCode||"").replace(/\D/g,"").slice(0,5),city=clean(b.city,100),tradeId=clean(b.tradeId,80),origin=allowedOrigin(req);if(!origin)return json({error:"Nicht zugelassener Portal-Ursprung"},403);if(!emailOk(email)||!passwordOk(password)||!name||!address||postalCode.length!==5||!city||!tradeId)return json({error:"Bitte Pflichtfelder und Passwortanforderungen vollständig erfüllen"},422);const snapshot=await loadRuntime(service),trade=array(snapshot.state.trades).find(x=>x.id===tradeId&&x.onboarding!==false);if(!trade)return json({error:"Gewerk ist nicht verfügbar"},422);if(array(snapshot.state.users).some(x=>String(x.email).toLowerCase()===email))return json({error:"Für diese E-Mail-Adresse besteht bereits ein Zugang"},409);const sourceUserId=identifier("u-basic"),partnerId=identifier("p-basic"),organizationId=identifier("org-basic");await service.from("identity_imports").upsert({source_user_id:sourceUserId,email,display_name:name,role:"partner_basic",active:true,activation_status:"pending"});const {data,error}=await service.auth.admin.generateLink({type:"signup",email,password,options:{redirectTo:origin}});if(error||!data?.properties?.action_link)return json({error:"Supabase-Zugang konnte nicht vorbereitet werden"},409);await service.from("identity_imports").update({auth_user_id:data.user?.id||null,activation_status:"invited"}).eq("source_user_id",sourceUserId);array(snapshot.state.users).push({id:sourceUserId,name,email,role:"partner_basic",active:true,createdAt:new Date().toISOString()});array(snapshot.state.partnerOrganizations).push({id:organizationId,name:company,type:tradeId==="BROKER"?"basic_broker":"basic_partner",address,postalCode,city,createdAt:new Date().toISOString()});array(snapshot.state.partners).push({id:partnerId,userId:sourceUserId,organizationId,company,contact:name,email,address,postalCode,city,tradeIds:[tradeId],primaryTradeId:tradeId,postalCodes:[],status:"invited",lifecycle:"invited",plan:"basic",partnerCategory:tradeId==="BROKER"?"broker":"equipment",createdAt:new Date().toISOString()});await replace(service,snapshot,"partner_basic.registration_requested","partner",partnerId);await sendMail(email,"Partner-Basic-Zugang bestätigen",`Hallo ${name},\n\nbitte bestätigen Sie Ihre E-Mail-Adresse:\n${data.properties.action_link}`);return json({message:"Bitte bestätigen Sie die Registrierung über die versendete E-Mail.",mailStatus:"sent"},202)}
  if(req.method==="POST"&&path==="/password/forgot"){const b=await req.json(),email=clean(b.email,254).toLowerCase(),origin=allowedOrigin(req);if(!origin)return json({error:"Nicht zugelassener Portal-Ursprung"},403);if(emailOk(email)){const {data}=await service.auth.admin.generateLink({type:"recovery",email,options:{redirectTo:`${origin}/passwort-zuruecksetzen`}});if(data?.properties?.action_link)await sendMail(email,"Passwort zurücksetzen",`Über diesen sicheren Link können Sie ein neues Passwort vergeben:\n${data.properties.action_link}`)}return json({message:"Wenn ein aktiver Zugang besteht, wurde eine E-Mail zum Zurücksetzen versendet."},202)}
  return json({error:"Route nicht gefunden"},404);
}catch(error){console.error(error);return json({error:error instanceof Error?error.message:"Öffentlicher Portalvorgang fehlgeschlagen"},500)}});
