import { array, isAdmin, publicRuntimeUser, scopedProperties, sourcePartner, type PortalProfile, type RuntimeState } from "./runtime.ts";

const forbidden=()=>({status:403,body:{error:"Keine Berechtigung"}});
const ok=(body:unknown)=>({status:200,body});

export function readRoute(path:string,state:RuntimeState,profile:PortalProfile,sourceUserId:string|null,email:string|null){
  const admin=isAdmin(profile), partner=sourcePartner(state,sourceUserId), properties=scopedProperties(state,profile,sourceUserId);
  const propertyIds=new Set(properties.map(x=>x.id));
  const scoped=(key:string)=>array(state[key]).filter(x=>!x.propertyId||propertyIds.has(x.propertyId));
  const customers=array(state.customers),partners=array(state.partners),salesFiles=scoped("salesFiles"),valuations=scoped("valuations"),postal=array(state.postalDirectory);
  const adminOnly=()=>admin?null:forbidden();
  if(path==="/account")return ok({account:{id:profile.id,name:profile.display_name,email,role:profile.role,createdAt:profile.created_at},partner});
  if(path==="/customers")return admin?ok({customers:array(state.customers),properties,source:"supabase"}):forbidden();
  if(path==="/production/customers")return admin?ok({customers:array(state.customers),counts:{visible:array(state.customers).length,hidden:array(state.productionCustomerDeletions).length},sort:"registeredAt:desc",registrationSummary:{},sourceUserCount:array(state.users).length,hiddenCount:array(state.productionCustomerDeletions).length,importedAt:(state.meta as Record<string,unknown>)?.createdAt||null,pendingSourceSync:false}):forbidden();
  if(path==="/partners")return admin?ok({partners:array(state.partners),trades:array(state.trades),organizations:array(state.partnerOrganizations),roleTemplates:array(state.partnerRoleTemplates),licensePolicy:{includedPostalCodes:2},source:"supabase"}):forbidden();
  if(path==="/assignments")return admin?ok({assignments:array(state.assignments),partners:array(state.partners),properties:array(state.properties),trades:array(state.trades)}):forbidden();
  if(path==="/cases")return ok({cases:scoped("serviceCases"),serviceRecords:scoped("partnerServiceRecords"),equipment:scoped("equipmentRecords"),customers:admin?array(state.customers):[],properties});
  if(path==="/sales")return ok({salesFiles:scoped("salesFiles"),valuations:scoped("valuations"),properties});
  if(path==="/campaigns")return admin?ok({campaigns:array(state.campaigns),trades:array(state.trades),regions:[],types:["weather","regulation","funding","manufacturer","maintenance"]}):forbidden();
  if(path==="/role-profiles")return profile.role==="super_admin"?ok({roles:array(state.roleProfiles),trades:array(state.trades),plans:["standard","premium"],organizations:array(state.partnerOrganizations),accounts:array(state.users).map(publicRuntimeUser),permissionCatalog:[]}):forbidden();
  if(path==="/partner-role-templates")return admin?ok({roles:array(state.partnerRoleTemplates),trades:array(state.trades),permissionCatalog:[]}):forbidden();
  if(path==="/admin/users")return profile.role==="super_admin"?ok({users:array(state.users).map(publicRuntimeUser),partners:array(state.partners)}):forbidden();
  if(path==="/opportunity-engine")return ok({scope:admin?"admin":"partner",definitions:array(state.triggerDefinitions),events:array(state.triggerEvents),affectedProperties:scoped("affectedProperties"),opportunities:admin?array(state.partnerOpportunities):array(state.partnerOpportunities).filter(x=>x.partnerId===partner?.id),customerActions:scoped("customerActions"),templates:array(state.customerActionTemplates),partners:admin?array(state.partners):partner?[partner]:[],kpis:{},categories:[],queue:array(state.opportunityJobs)});
  if(path==="/partner/workbench")return partner?ok({partner,properties,equipment:scoped("equipmentRecords"),serviceRecords:scoped("partnerServiceRecords"),cases:scoped("serviceCases"),offers:array(state.partnerOffers).filter(x=>x.partnerId===partner.id),trades:array(state.trades)}):forbidden();
  if(path==="/audit")return admin?ok({audit:array(state.audit).map(x=>({...x,detail:undefined}))}):forbidden();
  if(path==="/postal-codes")return ok({postalCodes:array(state.postalDirectory),trades:array(state.trades)});
  if(path==="/portfolio/risks")return admin?ok(array(state.properties).map(property=>({property,score:0,reasons:[]}))):forbidden();
  if(path==="/admin-light-dashboard"){
    if(profile.role!=="admin_light")return forbidden();
    const invitations=array(state.customerInvitations),now=Date.now();
    return ok({kpis:{customers:customers.length,properties:array(state.properties).length,partners:partners.filter(x=>x.status==="active").length,pendingInvitations:invitations.filter(x=>x.status==="pending"&&Date.parse(String(x.expiresAt||0))>=now).length,criticalCustomers:customers.filter(c=>!array(state.properties).some(p=>p.customerId===c.id)).length,pausedPartners:partners.filter(x=>x.status==="paused").length},recentInvitations:invitations.slice(0,6).map(({tokenHash,...x})=>x),scope:{customerData:"operativer Supportzugriff",roleConfiguration:false,triggerMutation:false}});
  }
  if(path==="/broker/customers"){
    if(profile.role!=="broker_partner")return forbidden();
    const rows=properties.map(property=>{const customer=customers.find(c=>c.id===property.customerId),salesFile=salesFiles.find(x=>x.propertyId===property.id),mandate=array(state.brokerMandates).find(x=>x.salesFileId===salesFile?.id),closing=array(state.brokerClosings).find(x=>x.salesFileId===salesFile?.id),stage=closing?"mandated":mandate?.acceptedAt?"mandated":salesFile?.status==="ready"?"sales_ready":"valuation_requested";return{customer:{id:customer?.id,name:customer?.name,email:customer?.email,phone:customer?.phone},property,salesFile:salesFile||null,stage,requestAt:salesFile?.requestedAt||null,readyAt:salesFile?.releasedAt||null,mandateAt:mandate?.acceptedAt||null,closingAt:closing?.notarizationDate||null,addressVerification:(state.propertyAddressVerifications as Record<string,Record<string,unknown>>)?.[String(property.id)]?.verified?"verified":"unverified"}});
    return ok({rows,counts:{total:rows.length,valuationRequested:rows.filter(x=>x.stage==="valuation_requested").length,salesReady:rows.filter(x=>x.stage==="sales_ready").length,mandated:rows.filter(x=>x.stage==="mandated").length},stages:[{id:"valuation_requested",label:"Verkehrswertermittlung angefragt"},{id:"sales_ready",label:"Verkaufsbereit"},{id:"mandated",label:"Mandatiert"}],dataQuality:{note:"Stufen werden objektbezogen aus Verkaufsakte, Maklervertrag und Kundenannahme abgeleitet."}});
  }
  if(path==="/broker-dashboard"){
    if(profile.role!=="broker_partner"||!partner)return forbidden();const cases=array(state.partnerCases).filter(x=>x.partnerId===partner.id&&x.kind==="sales_mandate"),mandates=cases.filter(x=>x.mandateReceivedAt),averageCompleteness=salesFiles.length?Math.round(salesFiles.reduce((n,x)=>n+Number(x.completeness||0),0)/salesFiles.length):0;
    return ok({partner:{id:partner.id,company:partner.company,contact:partner.contact},kpis:{assignedProperties:properties.length,salesReady:salesFiles.filter(x=>x.status==="ready").length,mandates:mandates.length,mandateRate:cases.length?Math.round(mandates.length/cases.length*100):0,averageResponseHours:null,averageCompleteness,portfolioValue:properties.reduce((n,p)=>n+Number(p.value||0),0),marketingValue:salesFiles.filter(x=>x.status==="ready").reduce((n,x)=>n+Number(x.askingPrice||0),0),valuations:valuations.length},salesFiles:salesFiles.map(x=>({...x,property:properties.find(p=>p.id===x.propertyId),latestValuation:valuations.filter(v=>v.propertyId===x.propertyId).sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate)))[0]||null})),cases,score:{score:0,confidence:"provisional",metrics:{mandateRate:0,avgResponseHours:null}},privacy:{scoped:true,note:"Es werden ausschließlich explizit zugewiesene Verkaufsimmobilien ausgegeben."}});
  }
  if(path==="/partner-coverage"){
    if(adminOnly())return forbidden();const trades=array(state.trades).filter(t=>t.onboarding!==false),active=partners.filter(p=>p.status==="active"),states=[...new Set(postal.map(x=>x.state).filter(Boolean))].sort();const regions=states.map(region=>{const codes=postal.filter(x=>x.state===region).map(x=>x.postalCode),byTrade=trades.map(t=>{const covered=new Set(active.filter(p=>p.primaryTradeId===t.id).flatMap(p=>Array.isArray(p.postalCodes)?p.postalCodes:[]).filter(z=>codes.includes(z)));return{tradeId:t.id,tradeName:t.name,covered:covered.size,total:codes.length,score:codes.length?Math.round(covered.size/codes.length*100):0}});return{state:region,totalPostalCodes:codes.length,score:byTrade.length?Math.round(byTrade.reduce((n,x)=>n+x.score,0)/byTrade.length):0,byTrade}});return ok({catalogSize:postal.length,overallScore:0,regions,trades,note:"Abdeckung auf Basis des hinterlegten PLZ-Katalogs."});
  }
  if(path==="/partner-geography"){
    if(adminOnly())return forbidden();const profiles=partners.map(p=>{const codes=Array.isArray(p.postalCodes)?p.postalCodes:[],regions=[...new Set(codes.map(code=>postal.find(x=>x.postalCode===code)?.state).filter(Boolean))];return{id:p.id,company:p.company,tradeId:p.primaryTradeId,trade:array(state.trades).find(t=>t.id===p.primaryTradeId)?.name||p.primaryTradeId,postalCodes:codes,regions,status:p.status,score:Number(p.score||0)}});return ok({profiles,summary:{total:profiles.length,active:profiles.filter(x=>x.status==="active").length}});
  }
  if(path==="/customer-coverage"){
    if(adminOnly())return forbidden();const profiles=customers.map(c=>{const owned=array(state.properties).filter(p=>p.customerId===c.id),code=String(owned[0]?.postalCode||c.postalCode||"");return{id:c.id,name:c.name,email:c.email,phone:c.phone,postalCode:code,region:postal.find(x=>x.postalCode===code)?.state||"Unbekannt",properties:owned.length,status:"registered",critical:owned.length===0,criticalReason:owned.length?null:"Registrierung vorhanden, aber noch keine Immobilie angelegt",addressVerification:"unverified"}});const states=[...new Set(postal.map(x=>x.state).filter(Boolean))].sort(),regions=states.map(region=>{const regional=profiles.filter(x=>x.region===region),codes=postal.filter(x=>x.state===region).map(x=>x.postalCode),covered=new Set(regional.map(x=>x.postalCode).filter(Boolean));return{state:region,totalPostalCodes:codes.length,coveredPostalCodes:covered.size,score:codes.length?Math.round(covered.size/codes.length*100):0,customers:regional.length,critical:regional.filter(x=>x.critical).length,customerIds:regional.map(x=>String(x.id)),pendingInvitations:0}});return ok({activeCustomers:profiles.length,catalogSize:postal.length,coveredPostalCodes:new Set(profiles.map(x=>x.postalCode).filter(Boolean)).size,overallScore:postal.length?Math.round(new Set(profiles.map(x=>x.postalCode).filter(Boolean)).size/postal.length*100):0,criticalCustomers:profiles.filter(x=>x.critical).length,pendingInvitations:0,expiredInvitations:0,regions,profiles,note:"Abdeckungsquote auf Basis des hinterlegten PLZ-Katalogs."});
  }
  return undefined;
}
