import { array, isAdmin, publicRuntimeUser, scopedProperties, sourcePartner, type PortalProfile, type RuntimeState } from "./runtime.ts";

const forbidden=()=>({status:403,body:{error:"Keine Berechtigung"}});
const ok=(body:unknown)=>({status:200,body});

export function readRoute(path:string,state:RuntimeState,profile:PortalProfile,sourceUserId:string|null,email:string|null){
  const admin=isAdmin(profile), partner=sourcePartner(state,sourceUserId), properties=scopedProperties(state,profile,sourceUserId);
  const propertyIds=new Set(properties.map(x=>x.id));
  const scoped=(key:string)=>array(state[key]).filter(x=>!x.propertyId||propertyIds.has(x.propertyId));
  const customers=array(state.customers),partners=array(state.partners),salesFiles=scoped("salesFiles"),valuations=scoped("valuations"),postal=array(state.postalDirectory);
  const adminOnly=()=>admin?null:forbidden();
  if(path==="/account"){const sourceUser=array(state.users).find(x=>String(x.id)===String(sourceUserId));return ok({account:{id:profile.id,name:profile.display_name,email,role:profile.role,phone:sourceUser?.phone||"",address:sourceUser?.address||"",postalCode:sourceUser?.postalCode||"",city:sourceUser?.city||"",createdAt:profile.created_at,emailImmutable:true},partner,organization:array(state.partnerOrganizations).find(x=>x.id===partner?.organizationId)||null});}
  if(path==="/customers")return admin?ok({customers:array(state.customers),properties,source:"supabase"}):forbidden();
  if(path==="/production/customers")return admin?ok({customers:array(state.customers),counts:{visible:array(state.customers).length,hidden:array(state.productionCustomerDeletions).length},sort:"registeredAt:desc",registrationSummary:{},sourceUserCount:array(state.users).length,hiddenCount:array(state.productionCustomerDeletions).length,importedAt:(state.meta as Record<string,unknown>)?.createdAt||null,pendingSourceSync:false}):forbidden();
  if(path==="/partners")return admin?ok({partners:array(state.partners),trades:array(state.trades),organizations:array(state.partnerOrganizations),roleTemplates:array(state.partnerRoleTemplates),licensePolicy:{includedPostalCodes:2},source:"supabase"}):forbidden();
  if(path==="/assignments")return admin?ok({assignments:array(state.assignments),partners:array(state.partners),properties:array(state.properties),trades:array(state.trades)}):forbidden();
  if(path==="/cases")return ok({cases:scoped("serviceCases"),serviceRecords:scoped("partnerServiceRecords"),equipment:scoped("equipmentRecords"),customers:admin?array(state.customers):[],properties});
  if(path==="/sales")return ok({salesFiles:scoped("salesFiles"),valuations:scoped("valuations"),properties});
  if(path==="/campaigns")return admin?ok({campaigns:array(state.campaigns),trades:array(state.trades),regions:[],types:["weather","regulation","funding","manufacturer","maintenance"]}):forbidden();
  if(path==="/role-profiles")return profile.role==="super_admin"?ok({roles:array(state.roleProfiles),trades:array(state.trades),plans:["standard","premium"],organizations:array(state.partnerOrganizations),accounts:array(state.users).map(publicRuntimeUser),permissionCatalog:[]}):forbidden();
  if(path==="/partner-role-templates")return admin?ok({roles:array(state.partnerRoleTemplates),trades:array(state.trades),permissionCatalog:[]}):forbidden();
  if(path==="/admin/users")return profile.role==="super_admin"?ok({users:array(state.users).map(publicRuntimeUser),partners:array(state.partners)}):forbidden();
  if(path==="/opportunity-engine")return ok({scope:admin?"admin":"partner",definitions:array(state.triggerDefinitions),events:array(state.triggerEvents),affectedProperties:scoped("affectedProperties"),opportunities:admin?array(state.partnerOpportunities):array(state.partnerOpportunities).filter(x=>x.partnerId===partner?.id),customerActions:scoped("customerActions"),templates:array(state.customerActionTemplates),partners:admin?array(state.partners):partner?[partner]:[],kpis:{},categories:[],queue:array(state.opportunityJobs)});
  if(path==="/partner/workbench"){if(!partner)return forbidden();const equipment=scoped("equipmentRecords").filter(x=>x.tradeId===partner.primaryTradeId),trade=array(state.trades).find(x=>x.id===partner.primaryTradeId),grouped=customers.map(customer=>{const owned=properties.filter(p=>p.customerId===customer.id).map(property=>({...property,equipment:equipment.filter(x=>x.propertyId===property.id).map(item=>({...item,health:item.health||{score:0,status:"review"}}))})).filter(x=>x.equipment.length||properties.some(p=>p.id===x.id));return{...customer,properties:owned}}).filter(x=>x.properties.length);return ok({partner:{...partner,tradeName:trade?.name||partner.primaryTradeId},customers:grouped,summary:{customers:grouped.length,properties:properties.length,critical:equipment.filter(x=>Number((x.health as Record<string,unknown>)?.score||0)<60).length,verified:equipment.filter(x=>(x.verification as Record<string,unknown>)?.status==="verified").length},equipment,serviceRecords:scoped("partnerServiceRecords"),cases:scoped("serviceCases"),offers:array(state.partnerOffers).filter(x=>x.partnerId===partner.id),trades:array(state.trades)});}
  if(path==="/audit")return admin?ok({audit:array(state.audit).map(x=>({...x,detail:undefined}))}):forbidden();
  if(path==="/postal-codes")return ok({postalCodes:array(state.postalDirectory),trades:array(state.trades)});
  if(path==="/portfolio/risks")return admin?ok(array(state.properties).map(property=>({property,score:0,reasons:[]}))):forbidden();
  if(path==="/admin-light-dashboard"){
    if(profile.role!=="admin_light")return forbidden();
    const invitations=array(state.customerInvitations),now=Date.now();
    return ok({kpis:{customers:customers.length,properties:array(state.properties).length,partners:partners.filter(x=>x.status==="active").length,pendingInvitations:invitations.filter(x=>x.status==="pending"&&Date.parse(String(x.expiresAt||0))>=now).length,criticalCustomers:customers.filter(c=>!array(state.properties).some(p=>p.customerId===c.id)).length,pausedPartners:partners.filter(x=>x.status==="paused").length},recentInvitations:invitations.slice(0,6).map(({tokenHash,...x})=>x),scope:{customerData:"operativer Supportzugriff",roleConfiguration:false,triggerMutation:false}});
  }
  if(path==="/broker/customers"){
    if(profile.role!=="broker_partner")return forbidden();
    const rows=properties.map(property=>{const customer=customers.find(c=>c.id===property.customerId),salesFile=salesFiles.find(x=>x.propertyId===property.id),mandate=array(state.brokerMandates).find(x=>x.salesFileId===salesFile?.id),closing=array(state.brokerClosings).find(x=>x.salesFileId===salesFile?.id),stage=closing?"mandated":mandate?.acceptedAt?"mandated":salesFile?.status==="ready"?"sales_ready":"valuation_requested";return{customer:{id:customer?.id,name:customer?.name,email:customer?.email,phone:customer?.phone},property,salesFile:salesFile||null,stage,requestAt:salesFile?.requestedAt||null,readyAt:salesFile?.releasedAt||null,mandateAt:mandate?.acceptedAt||null,closingAt:closing?.notarizationDate||null,addressVerification:(state.propertyAddressVerifications as Record<string,Record<string,unknown>>)?.[String(property.id)]?.verified?"verified":"unverified"}});
    return ok({rows,counts:{total:rows.length,valuationRequested:rows.filter(x=>x.stage==="valuation_requested").length,salesReady:rows.filter(x=>x.stage==="sales_ready").length,mandated:rows.filter(x=>x.stage==="mandated").length},stages:[{id:"valuation_requested",label:"Verkehrswertermittlung angefragt"},{id:"sales_ready",label:"Verkaufsbereit"},{id:"mandated",label:"Mandatiert"}],dataQuality:{note:"Stufen werden objektbezogen aus Verkaufsakte, Maklervertrag und Kundenannahme abgeleitet."}});
  }
  if(path==="/broker-dashboard"){
    if(profile.role!=="broker_partner"||!partner)return forbidden();const cases=array(state.partnerCases).filter(x=>x.partnerId===partner.id&&x.kind==="sales_mandate"),mandates=cases.filter(x=>x.mandateReceivedAt),averageCompleteness=salesFiles.length?Math.round(salesFiles.reduce((n,x)=>n+Number(x.completeness||0),0)/salesFiles.length):0;
    return ok({partner:{id:partner.id,company:partner.company,contact:partner.contact},kpis:{assignedProperties:properties.length,salesReady:salesFiles.filter(x=>x.status==="ready").length,mandates:mandates.length,mandateRate:cases.length?Math.round(mandates.length/cases.length*100):0,averageResponseHours:null,averageCompleteness,portfolioValue:properties.reduce((n,p)=>n+Number(p.value||0),0),marketingValue:salesFiles.filter(x=>x.status==="ready").reduce((n,x)=>n+Number(x.askingPrice||0),0),valuations:valuations.length},salesFiles:salesFiles.map(x=>({...x,property:properties.find(p=>p.id===x.propertyId),latestValuation:valuations.filter(v=>v.propertyId===x.propertyId).sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate)))[0]||null})),cases,score:{score:0,confidence:"provisional",metrics:{mandateRate:0,avgResponseHours:null}},privacy:{scoped:true,note:"Es werden ausschließlich explizit zugewiesene Verkaufsimmobilien ausgegeben."}});
  }
  if(path==="/partner-coverage"){
    if(adminOnly())return forbidden();const trades=array(state.trades).filter(t=>t.onboarding!==false),active=partners.filter(p=>p.status==="active"),states=[...new Set(postal.map(x=>x.state).filter(Boolean))].sort();const regions=states.map(region=>{const codes=postal.filter(x=>x.state===region).map(x=>x.postalCode),byTrade=trades.map(t=>{const covered=new Set(active.filter(p=>p.primaryTradeId===t.id).flatMap(p=>Array.isArray(p.postalCodes)?p.postalCodes:[]).filter(z=>codes.includes(z)));return{tradeId:t.id,tradeName:t.name,covered:covered.size,total:codes.length,score:codes.length?Math.round(covered.size/codes.length*100):0}});return{state:region,totalPostalCodes:codes.length,score:byTrade.length?Math.round(byTrade.reduce((n,x)=>n+x.score,0)/byTrade.length):0,byTrade}});return ok({catalogSize:postal.length,overallScore:0,regions,trades,note:"Abdeckung auf Basis des hinterlegten PLZ-Katalogs."});
  }
  if(path==="/partner-geography"){
    if(adminOnly())return forbidden();const profiles=partners.map(p=>{const codes=Array.isArray(p.postalCodes)?p.postalCodes:[],regions=[...new Set(codes.map(code=>postal.find(x=>x.postalCode===code)?.state).filter(Boolean))];return{id:p.id,company:p.company,tradeId:p.primaryTradeId,trade:array(state.trades).find(t=>t.id===p.primaryTradeId)?.name||p.primaryTradeId,postalCodes:codes,regions,status:p.status,score:Number(p.score||0)}});return ok({profiles,summary:{total:profiles.length,active:profiles.filter(x=>x.status==="active").length}});
  }
  if(path==="/customer-coverage"){
    if(adminOnly())return forbidden();const profiles=customers.map(c=>{const owned=array(state.properties).filter(p=>p.customerId===c.id),code=String(owned[0]?.postalCode||c.postalCode||"");return{id:c.id,name:c.name,email:c.email,phone:c.phone,postalCode:code,region:postal.find(x=>x.postalCode===code)?.state||"Unbekannt",properties:owned.length,status:"registered",critical:owned.length===0,criticalReason:owned.length?null:"Registrierung vorhanden, aber noch keine Immobilie angelegt",addressVerification:"unverified"}});const states=[...new Set(postal.map(x=>x.state).filter(Boolean))].sort(),regions=states.map(region=>{const regional=profiles.filter(x=>x.region===region),codes=postal.filter(x=>x.state===region).map(x=>x.postalCode),covered=new Set(regional.map(x=>x.postalCode).filter(Boolean));return{state:region,totalPostalCodes:codes.length,coveredPostalCodes:covered.size,score:codes.length?Math.round(covered.size/codes.length*100):0,customers:regional.length,critical:regional.filter(x=>x.critical).length,customerIds:regional.map(x=>String(x.id)),pendingInvitations:0}});return ok({activeCustomers:profiles.length,catalogSize:postal.length,coveredPostalCodes:new Set(profiles.map(x=>x.postalCode).filter(Boolean)).size,overallScore:postal.length?Math.round(new Set(profiles.map(x=>x.postalCode).filter(Boolean)).size/postal.length*100):0,criticalCustomers:profiles.filter(x=>x.critical).length,pendingInvitations:0,expiredInvitations:0,regions,profiles,note:"Abdeckungsquote auf Basis des hinterlegten PLZ-Katalogs."});
  }
  if(path==="/analytics/overview"){
    if(!admin)return forbidden();const profiles=customers.map(customer=>{const owned=array(state.properties).filter(p=>p.customerId===customer.id),ids=new Set(owned.map(p=>p.id)),equipment=array(state.equipmentRecords).filter(x=>ids.has(x.propertyId)),documents=array(state.documents).filter(x=>ids.has(x.propertyId||x.source_property_id)),completeness=owned.length?Math.min(100,Math.round((owned.filter(p=>p.address&&p.postalCode).length/owned.length*50)+(equipment.length?30:0)+(documents.length?20:0))):0,code=String(owned[0]?.postalCode||customer.postalCode||""),region=postal.find(x=>x.postalCode===code)?.state||"Unbekannt";return{id:customer.id,name:customer.name,email:customer.email,registeredAt:customer.registeredAt||customer.createdAt||null,lifecycle:owned.length?equipment.length?"data_entry":"onboarding":"registered",properties:owned.length,equipment:equipment.length,documents:documents.length,completeness,measurement:"unmeasured",sessions:0,lastActivity:null,region}}),regions:Record<string,{registered:number;properties:number;averageCompleteness:number}>={};for(const row of profiles){const r=regions[row.region]||{registered:0,properties:0,averageCompleteness:0};r.registered++;r.properties+=row.properties;r.averageCompleteness+=row.completeness;regions[row.region]=r;}for(const r of Object.values(regions))r.averageCompleteness=Math.round(r.averageCompleteness/Math.max(1,r.registered));return ok({summary:{registered:profiles.length,withProperty:profiles.filter(x=>x.properties).length,averageCompleteness:profiles.length?Math.round(profiles.reduce((n,x)=>n+x.completeness,0)/profiles.length):0,measuredUsers:0,active30:0},funnel:{registered:profiles.length,property:profiles.filter(x=>x.properties).length,equipment:profiles.filter(x=>x.equipment).length,document:profiles.filter(x=>x.documents).length},measurement:{startedAt:(state.analyticsStartedAt as string)||new Date().toISOString(),note:"Nutzungsdaten werden erst ab aktivierter Telemetrie gemessen."},regions,profiles});
  }
  if(path==="/system-overview"){
    if(profile.role!=="super_admin")return forbidden();return ok({application:{name:"eigenheimverwalter Pilot · Partner OS",version:"supabase-1",environment:"Supabase",releaseStatus:"Migration und Go-live-Prüfung",dataSource:"Dediziertes Pilot-Supabase-Projekt"},development:[{module:"Supabase-Datenmodell",status:"implemented",note:"Dediziertes Projekt, atomare Laufzeitstände und Audit-Protokoll."},{module:"Dokumentenspeicher",status:"implemented",note:"Private Buckets und kurzlebige signierte Abruflinks."},{module:"Render-Ablösung",status:"partial",note:"Backend portiert; dauerhaftes Frontend-Hosting wird finalisiert."}],services:[{category:"Backend & Datenbank",provider:"Supabase",purpose:"Auth, Datenbank, Storage und Edge Functions",integration:"Projekt rpniwtshbwjuesoeztyt",status:"connected",cost:"Tarifabhängig",dataFlow:"EU-Projektregion",lastSync:null,lastError:null},{category:"E-Mail",provider:"ALL-INKL",purpose:"Getrennte Partner-, Registrierungs- und Infokanäle",integration:"Supabase Mailgateway",status:"connected",cost:"Bestandstarif",dataFlow:"Serverseitiges SMTP",lastSync:null,lastError:null}],mail:{transport:"Supabase Edge / ALL-INKL"},security:{credentialsExposed:false,serverSideAcl:true,auditLogging:true}});
  }
  if(path==="/partner-performance"){
    if(!admin)return forbidden();const partnerCases=array(state.partnerCases),scores=partners.map(p=>{const cases=partnerCases.filter(x=>x.partnerId===p.id),accepted=cases.filter(x=>x.acceptedAt||x.mandateReceivedAt).length,completed=cases.filter(x=>x.completedAt||x.status==="completed").length,documented=cases.filter(x=>x.documents||x.invoiceReceivedAt).length,metrics={avgResponseHours:null,acceptance:cases.length?Math.round(accepted/cases.length*100):0,completion:cases.length?Math.round(completed/cases.length*100):0,mandateRate:cases.length?Math.round(cases.filter(x=>x.mandateReceivedAt).length/cases.length*100):0,offerAcceptance:0,documentation:cases.length?Math.round(documented/cases.length*100):0},score=cases.length?Math.round((metrics.acceptance+metrics.completion+metrics.documentation)/3):0;return{id:p.id,partner:p.company,cases:cases.length,score,critical:cases.length>=3&&score<60,confidence:cases.length>=3?"sufficient":cases.length?"provisional":"none",metrics}}).sort((a,b)=>a.score-b.score);return ok({scores,cases:partnerCases,partners:partners.map(p=>({id:p.id,company:p.company,primaryTradeId:p.primaryTradeId})),summary:{critical:scores.filter(x=>x.critical).length,provisional:scores.filter(x=>x.confidence==="provisional").length,average:Math.round(scores.filter(x=>x.confidence!=="none").reduce((n,x)=>n+x.score,0)/Math.max(1,scores.filter(x=>x.confidence!=="none").length))},method:{threshold:60,minCases:3,responseSlaHours:4,invoiceSlaHours:72}});
  }
  if(path==="/broker-ranking"){
    if(!admin)return forbidden();const brokers=partners.filter(x=>x.primaryTradeId==="BROKER"),ranking=brokers.map(p=>{const files=array(state.salesFiles).filter(x=>x.partnerId===p.id),mandates=array(state.brokerMandates).filter(x=>x.partnerId===p.id),closings=array(state.brokerClosings).filter(x=>x.partnerId===p.id),documentation=files.length?Math.round(files.reduce((n,x)=>n+Number(x.completeness||0),0)/files.length):0,mandateRate=files.length?Math.round(mandates.length/files.length*100):0,successRate=mandates.length?Math.round(closings.length/mandates.length*100):0,score=Math.round(mandateRate*.3+successRate*.3+documentation*.15+25);return{partner:p.company,partnerId:p.id,score,revenue:closings.reduce((n,x)=>n+Number(x.salePrice||0),0),mandates:mandates.length,mandateRate,successfulSales:closings.length,successRate,averageResponseHours:null,documentation}}).sort((a,b)=>b.score-a.score||b.revenue-a.revenue).slice(0,10);return ok({ranking,method:"Score: Reaktionszeit, Mandatsquote, erfolgreiche Vermittlungen und Aktenvollständigkeit.",generatedAt:new Date().toISOString()});
  }
  if(path==="/property-ranking"){
    if(!admin)return forbidden();const items=array(state.properties).map(property=>{const equipment=array(state.equipmentRecords).filter(x=>x.propertyId===property.id),services=array(state.partnerServiceRecords).filter(x=>x.propertyId===property.id),documents=array(state.documents).filter(x=>String(x.propertyId||x.source_property_id)===String(property.id)),verified=equipment.filter(x=>(x.verification as Record<string,unknown>)?.status==="verified").length,metrics={documentation:Math.min(100,documents.length*20),fileQuality:Math.min(100,documents.length*15),verification:equipment.length?Math.round(verified/equipment.length*100):0,serviceDensity:Math.min(100,services.length*20),equipment:Math.min(100,equipment.length*20),health:equipment.length?Math.round(equipment.reduce((n,x)=>n+Number((x.health as Record<string,unknown>)?.score||0),0)/equipment.length):0,maintenance:services.length?100:0},score=Math.round(Object.values(metrics).reduce((n,x)=>n+x,0)/Object.keys(metrics).length),customer=customers.find(x=>x.id===property.customerId);return{propertyId:property.id,ehvId:property.ehvId||property.id,customer:customer?.name||"–",city:property.city||"–",score,metrics,evidence:{documents:documents.length,equipment:equipment.length,services:services.length,verifiedEquipment:verified}}}).sort((a,b)=>b.score-a.score).slice(0,10).map((x,i)=>({...x,rank:i+1}));return ok({items,evaluated:array(state.properties).length});
  }
  if(path==="/referral"){
    if(!partner)return forbidden();const rows=array(state.referralLeads).filter(x=>x.partnerId===partner.id),registered=rows.filter(x=>x.status!=="pending").length;return ok({link:`/ref/${partner.referralCode||partner.id}`,stats:{referred:rows.length,registered,assigned:rows.filter(x=>x.propertyId||x.customerId).length},recent:rows.slice(0,10)});
  }
  if(path==="/partner-basic/profile"){if(!partner||!["partner_basic","referral_partner"].includes(profile.role))return forbidden();const trade=array(state.trades).find(x=>x.id===partner.primaryTradeId);return ok({partnerId:partner.id,company:partner.company,tradeId:partner.primaryTradeId||null,tradeName:trade?.name||"Allgemeine Empfehlung",referralOnly:Boolean(partner.referralOnly||profile.role==="referral_partner"),plan:partner.plan||"basic"});}
  if(path==="/partner-basic/dashboard"){if(!partner||!["partner_basic","referral_partner"].includes(profile.role))return forbidden();const invitations=array(state.partnerReferralInvitations).filter(x=>x.partnerId===partner.id),leads=array(state.referralLeads).filter(x=>x.partnerId===partner.id),mask=(value:unknown)=>{const text=String(value||""),[local,domain=""]=text.split("@");return local.slice(0,2)+"***@***."+(domain.split(".").at(-1)||"").slice(-2)},recent=invitations.slice(0,12).map(x=>({id:x.id,name:x.name,email:mask(x.email),address:x.address,postalCode:x.postalCode,city:x.city,status:x.status,createdAt:x.createdAt})),postalCounts=new Map<string,number>();for(const x of [...invitations,...leads]){const code=String(x.postalCode||"");if(code)postalCounts.set(code,(postalCounts.get(code)||0)+1)}const regions=[...postalCounts.entries()].map(([postalCode,count])=>{const p=postal.find(x=>x.postalCode===postalCode);return{postalCode,count,city:p?.city||"",state:p?.state||""}}).sort((a,b)=>b.count-a.count).slice(0,5),accepted=invitations.filter(x=>x.status==="accepted").length,successful=invitations.filter(x=>x.status==="successful").length;return ok({partner:{id:partner.id,company:partner.company,referralOnly:Boolean(partner.referralOnly||profile.role==="referral_partner")},kpis:{recommended:invitations.length,open:invitations.filter(x=>x.status==="pending").length,accepted,successful,mailQueued:invitations.length,registered:leads.length,conversionRate:invitations.length?Math.round(leads.length/invitations.length*100):0},regions,recent});}
  if(path==="/partner-basic/broker-properties"){if(!partner||profile.role!=="partner_basic"||partner.primaryTradeId!=="BROKER")return forbidden();const rows=properties.map(property=>{const customer=customers.find(x=>x.id===property.customerId),required=["address","postalCode","city","type","year","area","landArea"],missing=required.filter(key=>property[key]===null||property[key]===undefined||property[key]==="");return{customer:{id:customer?.id,name:customer?.name,email:customer?.email},property,missing,completeness:Math.round((required.length-missing.length)/required.length*100),phase4Value:Number(property.value||0)}});return ok({partner:{id:partner.id,company:partner.company},kpis:{customers:new Set(rows.map(x=>x.customer.id).filter(Boolean)).size,properties:rows.length,complete:rows.filter(x=>!x.missing.length).length,portfolioValue:rows.reduce((n,x)=>n+x.phase4Value,0)},rows});}
  const productionCustomerId=path.match(/^\/production\/customers\/([^/]+)$/)?.[1];
  if(productionCustomerId){if(!admin)return forbidden();const customer=customers.find(x=>String(x.id)===productionCustomerId);if(!customer)return{status:404,body:{error:"Kunde nicht gefunden"}};const owned=array(state.properties).filter(x=>String(x.customerId||x.user_id)===productionCustomerId),ownedIds=new Set(owned.map(x=>String(x.id))),related:Record<string,unknown[]>={};for(const [key,value] of Object.entries(state))if(Array.isArray(value)&&!["customers","properties","users"].includes(key)){const rows=value.filter(x=>x&&typeof x==="object"&&(ownedIds.has(String(x.propertyId||(x as Record<string,unknown>).property_id))||String(x.customerId||(x as Record<string,unknown>).user_id)===productionCustomerId));if(rows.length)related[key]=rows;}return ok({user:customer,properties:owned,related,locallyModified:false,sourceSyncStatus:"synchronized"});}
  const equipmentId=path.match(/^\/equipment\/([^/]+)$/)?.[1];
  if(equipmentId){const equipment=array(state.equipmentRecords).find(x=>String(x.id)===equipmentId);if(!equipment)return{status:404,body:{error:"Equipment nicht gefunden"}};if(!allowedProperties.has(equipment.propertyId))return forbidden();const property=properties.find(x=>x.id===equipment.propertyId),customer=customers.find(x=>x.id===property?.customerId);return ok({equipment,property,customer,offers:array(state.partnerOffers).filter(x=>x.equipmentId===equipmentId),serviceRecords:array(state.partnerServiceRecords).filter(x=>x.equipmentId===equipmentId),cases:array(state.serviceCases).filter(x=>x.equipmentId===equipmentId)});}
  const brokerFileId=path.match(/^\/broker\/sales-files\/([^/]+)$/)?.[1];
  if(brokerFileId){if(!admin&&profile.role!=="broker_partner")return forbidden();const file=salesFiles.find(x=>String(x.id)===brokerFileId);if(!file)return{status:404,body:{error:"Verkaufsakte nicht gefunden"}};const property=properties.find(x=>x.id===file.propertyId),customer=customers.find(x=>x.id===property?.customerId),adjustments=array(state.brokerValuationAdjustments).filter(x=>x.salesFileId===brokerFileId),documents=array(state.brokerSalesDocuments).filter(x=>x.salesFileId===brokerFileId);return ok({file,property,customer,phase4:{marketValue:Number(property?.value||file.calculatedValue||0),propertyType:property?.type||null,year:property?.year||null,livingArea:property?.area||null,landArea:property?.landArea||null},latestAdjustment:adjustments[0]||null,adjustments,documents,mandate:array(state.brokerMandates).find(x=>x.salesFileId===brokerFileId)||null,closing:array(state.brokerClosings).find(x=>x.salesFileId===brokerFileId)||null,addressVerification:(state.propertyAddressVerifications as Record<string,unknown>)?.[String(property?.id)]||null});}
  return undefined;
}
