import { array, clean, identifier, isAdmin, replaceRuntime, scopedProperties, sourcePartner, type PortalProfile, type RuntimeSnapshot } from "./runtime.ts";
import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { sendPortalMail } from "./mail.ts";
import { normalizeEquipmentFields } from "./equipment-fields.mjs";
import { applyPartnerLicenseChange, partnerLicenseSummary } from "./partner-license.mjs";

type Context={service:SupabaseClient;snapshot:RuntimeSnapshot;profile:PortalProfile;sourceUserId:string|null;body:Record<string,unknown>};
type MailIntent={channel:"partner"|"registration"|"info";recipientEmail:string;subject:string;message:string};
const fail=(message:string,status=422)=>{throw Object.assign(new Error(message),{status})};
const collection=(snapshot:RuntimeSnapshot,key:string)=>{const rows=array(snapshot.state[key]);snapshot.state[key]=rows;return rows};
const digest=async(value:string)=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("");

export async function writeRoute(method:string,path:string,ctx:Context){
  const {snapshot,profile,sourceUserId,service,body}=ctx,state=snapshot.state,admin=isAdmin(profile),partner=sourcePartner(state,sourceUserId);
  const allowedProperties=new Set(scopedProperties(state,profile,sourceUserId).map(x=>x.id));
  let result:unknown,action="",entityType="",entityId="",mailAfterCommit:MailIntent|null=null;
  if(method==="PATCH"&&path==="/account"){
    const sourceUser=collection(snapshot,"users").find(x=>String(x.id)===String(sourceUserId));if(!sourceUser)fail("Quellkonto nicht gefunden",404);for(const [key,max] of [["name",120],["phone",50],["address",180],["postalCode",5],["city",100]] as const)if(key in body)sourceUser[key]=clean(body[key],max);if(sourceUser.postalCode&&!/^\d{5}$/.test(String(sourceUser.postalCode)))fail("Postleitzahl muss fünfstellig sein");result={account:{...sourceUser,email:undefined,passwordHash:undefined}};action="account.updated";entityType="portal_user";entityId=profile.id;
  } else if(method==="POST"&&path==="/referral/invitations"){
    if(!partner||!["partner_basic","referral_partner"].includes(profile.role))fail("Keine Berechtigung",403);const name=clean(body.name,120),email=clean(body.email,254).toLowerCase(),address=clean(body.address,180),postalCode=String(body.postalCode||"").replace(/\D/g,"").slice(0,5),city=clean(body.city,100),tradeId=profile.role==="referral_partner"?null:String(partner.primaryTradeId||"");if(!name||!email.includes("@")||!address||postalCode.length!==5||!city||body.consentConfirmed!==true)fail("Kundendaten und Einwilligung sind vollständig erforderlich");const siteUrl=clean(body.siteUrl,300);if(!/^https:\/\//.test(siteUrl))fail("Sichere Portaladresse fehlt");const token=crypto.randomUUID()+crypto.randomUUID(),item={id:identifier("ref-invite"),tokenHash:await digest(token),partnerId:partner.id,tradeId,referralOnly:profile.role==="referral_partner",name,email,address,postalCode,city,status:"pending",createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*86400000).toISOString()};collection(snapshot,"partnerReferralInvitations").unshift(item);result={invitation:{id:item.id,status:item.status,expiresAt:item.expiresAt}};action="referral.invitation.created";entityType="referral_invitation";entityId=item.id;mailAfterCommit={channel:"registration",recipientEmail:email,subject:"Empfehlung von eigenheimverwalter bestätigen",message:`${partner.company} hat Sie empfohlen. Bitte prüfen und bestätigen Sie die Angaben:\n${siteUrl.replace(/\/$/,"")}/empfehlung/${token}`};
  } else if(method==="POST"&&path==="/assignments"){
    if(!admin)fail("Keine Berechtigung",403); const rows=collection(snapshot,"assignments");
    const partnerId=clean(body.partnerId,100),propertyId=clean(body.propertyId,100),tradeId=clean(body.tradeId,100);
    if(!array(state.partners).some(x=>x.id===partnerId)||!array(state.properties).some(x=>x.id===propertyId)||!tradeId)fail("Partner, Objekt und Gewerk sind erforderlich");
    result={id:identifier("assignment"),partnerId,propertyId,tradeId,status:"active",overrideRegion:Boolean(body.overrideRegion),accessStart:new Date().toISOString(),accessEnd:body.accessEnd||null};rows.unshift(result as Record<string,unknown>);action="assignment.created";entityType="assignment";entityId=String((result as Record<string,unknown>).id);
  } else if(method==="POST"&&path==="/cases"){
    const propertyId=clean(body.propertyId,100);if(!allowedProperties.has(propertyId))fail("Kein Zugriff auf dieses Objekt",403);
    result={id:identifier("case"),propertyId,title:clean(body.title,180),category:clean(body.category,100),status:"new",priority:["low","medium","high"].includes(String(body.priority))?body.priority:"medium",partnerId:body.partnerId||partner?.id||null,updatedAt:new Date().toISOString(),documents:[]};if(!(result as Record<string,unknown>).title)fail("Titel ist erforderlich");collection(snapshot,"serviceCases").unshift(result as Record<string,unknown>);action="case.created";entityType="case";entityId=String((result as Record<string,unknown>).id);
  } else if(method==="POST"&&path==="/valuations"){
    if(!admin&&profile.role!=="broker_partner")fail("Keine Berechtigung",403);const propertyId=clean(body.propertyId,100);if(!allowedProperties.has(propertyId))fail("Kein Zugriff auf dieses Objekt",403);
    const value=Number(body.value);if(!Number.isFinite(value)||value<=0)fail("Gültiger Wert erforderlich");result={id:identifier("valuation"),propertyId,source:clean(body.source,100)||"Makler",value,effectiveDate:body.effectiveDate||new Date().toISOString().slice(0,10),createdBy:sourceUserId,note:clean(body.note,1000)};collection(snapshot,"valuations").unshift(result as Record<string,unknown>);action="valuation.created";entityType="valuation";entityId=String((result as Record<string,unknown>).id);
  } else if(method==="POST"&&path==="/campaigns"){
    if(profile.role!=="super_admin")fail("Keine Berechtigung",403);result={id:identifier("campaign"),title:clean(body.title,160),type:clean(body.type,80),status:"draft",source:{title:clean(body.sourceTitle,200),url:clean(body.sourceUrl,500)},regions:Array.isArray(body.regions)?body.regions:[],tradeIds:Array.isArray(body.tradeIds)?body.tradeIds:[],createdAt:new Date().toISOString(),createdBy:sourceUserId};if(!(result as Record<string,unknown>).title)fail("Titel ist erforderlich");collection(snapshot,"campaigns").unshift(result as Record<string,unknown>);action="campaign.created";entityType="campaign";entityId=String((result as Record<string,unknown>).id);
  } else if(method==="POST"&&path==="/customer-invitations"){
    if(!admin)fail("Keine Berechtigung",403);const firstName=clean(body.firstName,80),lastName=clean(body.lastName,80),email=clean(body.email,254).toLowerCase(),phone=clean(body.phone,50),address=clean(body.address,180),postalCode=String(body.postalCode||"").replace(/\D/g,"").slice(0,5),city=clean(body.city,100),siteUrl=clean(body.siteUrl,300);if(!firstName||!lastName||!email.includes("@")||!phone||!address||postalCode.length!==5||!city||!/^https:\/\//.test(siteUrl))fail("Vollständige Kundendaten und sichere Portaladresse sind erforderlich");if(collection(snapshot,"customerInvitations").some(x=>String(x.email).toLowerCase()===email&&x.status==="pending"))fail("Für diese E-Mail besteht bereits eine offene Einladung",409);const token=crypto.randomUUID()+crypto.randomUUID(),invitation={id:identifier("invite"),tokenHash:await digest(token),firstName,lastName,email,phone,address,postalCode,city,status:"pending",createdBy:sourceUserId,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*86400000).toISOString(),acceptedAt:null};collection(snapshot,"customerInvitations").unshift(invitation);result={invitation:{id:invitation.id,email,status:invitation.status,expiresAt:invitation.expiresAt},registrationLink:`${siteUrl.replace(/\/$/,"")}/registrierung/${token}`};action="customer.invitation.created";entityType="customer_invitation";entityId=invitation.id;mailAfterCommit={channel:"registration",recipientEmail:email,subject:"Ihre Registrierung bei eigenheimverwalter",message:`Hallo ${firstName} ${lastName},\n\nüber diesen sicheren Link können Sie Ihre Registrierung abschließen:\n${(result as Record<string,unknown>).registrationLink}`};
  } else if(method==="POST"&&path==="/partners"){
    if(!admin)fail("Keine Berechtigung",403);
    const company=clean(body.company,180),contact=clean(body.contact,180),email=clean(body.email,254).toLowerCase(),tradeIds=Array.isArray(body.tradeIds)?[...new Set(body.tradeIds.map(x=>clean(x,100)).filter(Boolean))]:[clean(body.primaryTradeId||body.tradeId,100)].filter(Boolean),postalCodes=Array.isArray(body.postalCodes)?[...new Set(body.postalCodes.map(x=>String(x).replace(/\D/g,"").slice(0,5)))]:[],siteUrl=clean(body.siteUrl,300);
    if(!company||!email.includes("@"))fail("Firma und E-Mail sind erforderlich");if(tradeIds.length!==1)fail("Pro Partnerkonto muss genau ein Gewerk ausgewählt werden");if(!/^https:\/\//.test(siteUrl))fail("Sichere Portaladresse fehlt");if(!postalCodes.length||postalCodes.some(code=>!/^\d{5}$/.test(code)||!collection(snapshot,"postalDirectory").some(x=>x.postalCode===code)))fail("Mindestens eine gültige Postleitzahl aus dem Katalog ist erforderlich");
    if(collection(snapshot,"partners").some(x=>String(x.email).toLowerCase()===email)||collection(snapshot,"users").some(x=>String(x.email).toLowerCase()===email))fail("Diese Login-E-Mail ist bereits zugeordnet",409);const occupied=postalCodes.filter(code=>collection(snapshot,"partners").some(x=>x.status==="active"&&x.primaryTradeId===tradeIds[0]&&Array.isArray(x.postalCodes)&&x.postalCodes.includes(code)));if(occupied.length)fail(`Für dieses Gewerk bereits belegt: ${occupied.join(", ")}`,409);
    let organization=collection(snapshot,"partnerOrganizations").find(x=>String(x.name).toLowerCase()===company.toLowerCase());if(!organization){organization={id:identifier("organization"),name:company,type:"specialist",address:"",postalCode:"",city:"",createdAt:new Date().toISOString()};collection(snapshot,"partnerOrganizations").push(organization)}
    const partnerId=identifier("partner"),token=crypto.randomUUID()+crypto.randomUUID(),invitation={id:identifier("partner-invite"),partnerId,tokenHash:await digest(token),status:"pending",createdBy:sourceUserId,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*86400000).toISOString()},partnerRecord={id:partnerId,organizationId:organization.id,company,contact,email,status:"invited",lifecycle:"invited",partnerCategory:tradeIds[0]==="BROKER"?"broker":"equipment",equipmentTypeId:tradeIds[0].startsWith("EQUIP_")?tradeIds[0]:null,roleTemplateId:collection(snapshot,"partnerRoleTemplates").find(x=>x.tradeId===tradeIds[0]&&x.status==="active")?.id||null,tradeIds,primaryTradeId:tradeIds[0],postalCodes,onboarding:10,lastContact:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()};collection(snapshot,"partners").unshift(partnerRecord);collection(snapshot,"partnerInvitations").unshift(invitation);result={...partnerRecord,invitation:{status:"pending",expiresAt:invitation.expiresAt}};action="partner.trade_account.created";entityType="partner";entityId=partnerId;const trade=collection(snapshot,"trades").find(x=>x.id===tradeIds[0]);mailAfterCommit={channel:"partner",recipientEmail:email,subject:"Ihr Partnerzugang bei eigenheimverwalter",message:`Hallo ${contact||company}, Sie wurden als ${trade?.name||"Kooperationspartner"} eingeladen. Über den sicheren Link vergeben Sie Ihr Passwort und aktivieren den Zugang:\n${siteUrl.replace(/\/$/,"")}/partner-einladung/${token}`};
  } else if(method==="PATCH"&&path.match(/^\/partners\/[^/]+\/license$/)){
    if(!admin)fail("Keine Berechtigung",403);const partnerId=path.split("/")[2],selected=collection(snapshot,"partners").find(x=>String(x.id)===partnerId);if(!selected)fail("Partner nicht gefunden",404);const postalCodes=Array.isArray(body.postalCodes)?[...new Set(body.postalCodes.map(x=>String(x).replace(/\D/g,"").slice(0,5)))]:[];if(!postalCodes.length||postalCodes.some(code=>!collection(snapshot,"postalDirectory").some(x=>x.postalCode===code)))fail("Alle PLZ müssen aus dem hinterlegten Katalog stammen");const occupied=postalCodes.filter(code=>collection(snapshot,"partners").some(x=>x.id!==selected.id&&x.status==="active"&&x.primaryTradeId===selected.primaryTradeId&&Array.isArray(x.postalCodes)&&x.postalCodes.includes(code)));if(occupied.length)fail(`Für dieses Gewerk bereits belegt: ${occupied.join(", ")}`,409);const changes=applyPartnerLicenseChange(selected,{postalCodes,cooperationStart:clean(body.cooperationStart,10),contractEnd:clean(body.contractEnd,10),reservationDate:clean(body.reservationDate,10),extensionMonths:Number(body.extensionMonths||12)});if(changes.error==="reservation_date_required")fail("Für neu hinzugebuchte PLZ ist das Reservierungsdatum erforderlich");selected.lastContact=new Date().toISOString().slice(0,10);result={partner:{...selected,licenseSummary:partnerLicenseSummary(selected)},changes:{added:changes.added,removed:changes.removed}};action="partner.license.updated";entityType="partner";entityId=partnerId;
  } else if(method==="POST"&&path.match(/^\/partners\/[^/]+\/email$/)){
    if(!admin)fail("Keine Berechtigung",403);const partnerId=path.split("/")[2],selected=collection(snapshot,"partners").find(x=>String(x.id)===partnerId);if(!selected)fail("Partner nicht gefunden",404);const subject=clean(body.subject,180),message=clean(body.message,5000);if(!subject||!message)fail("Betreff und Nachricht sind erforderlich");const outbox={id:identifier("mail"),partnerId,to:selected.email,from:"partner@eigenheimverwalter.de",subject,message,status:"queued",createdAt:new Date().toISOString(),createdBy:sourceUserId};collection(snapshot,"emailOutbox").unshift(outbox);result={mail:outbox,configuration:{provider:"ALL-INKL",channel:"partner"}};action="partner.email.queued";entityType="partner";entityId=partnerId;mailAfterCommit={channel:"partner",recipientEmail:String(selected.email),subject,message};
  } else if(method==="POST"&&path==="/system/mail-test"){
    if(profile.role!=="super_admin")fail("Nur Admin Plus darf Testmails versenden",403);const channel=String(body.channel),to=clean(body.to,254).toLowerCase();if(!["partner","registration","info"].includes(channel)||!to.includes("@"))fail("Gültiger Empfänger und Versandkanal erforderlich");result={status:"queued",channel};action="mail.test.queued";entityType="mail_channel";entityId=channel;mailAfterCommit={channel:channel as MailIntent["channel"],recipientEmail:to,subject:`eigenheimverwalter SMTP-Test · ${channel}`,message:`Kontrollierte Testnachricht aus dem Pilot-Portal.\nVersandkanal: ${channel}\nZeitpunkt: ${new Date().toISOString()}`};
  } else if(method==="POST"&&path==="/broker/sales-files"){
    if(!admin&&profile.role!=="broker_partner")fail("Keine Berechtigung",403);const propertyId=clean(body.propertyId,100);if(!allowedProperties.has(propertyId))fail("Kein Zugriff",403);const existing=collection(snapshot,"salesFiles").find(x=>x.propertyId===propertyId&&x.status!=="archived");if(existing)result=existing;else{result={id:identifier("sales"),propertyId,partnerId:partner?.id||null,status:"valuation_requested",requestedAt:new Date().toISOString(),completeness:0,documents:[],createdBy:sourceUserId};collection(snapshot,"salesFiles").unshift(result as Record<string,unknown>);}action="broker.sales_file.created";entityType="sales_file";entityId=String((result as Record<string,unknown>).id);
  } else if(method==="POST"&&path.match(/^\/properties\/([^/]+)\/equipment$/)){
    const propertyId=path.match(/^\/properties\/([^/]+)\/equipment$/)![1];if(!allowedProperties.has(propertyId))fail("Kein Zugriff",403);if(!partner)fail("Kein Partnerkonto",403);const existing=collection(snapshot,"equipmentRecords").find(x=>x.propertyId===propertyId&&x.tradeId===partner.primaryTradeId);if(existing)result={equipment:existing,idempotent:true};else{const equipment={id:identifier("equipment"),propertyId,tradeId:partner.primaryTradeId,label:clean(body.label,160)||partner.primaryTradeId,status:"draft",details:{},verification:{status:"unverified"},createdAt:new Date().toISOString(),createdBy:sourceUserId};collection(snapshot,"equipmentRecords").unshift(equipment);result={equipment,idempotent:false};}action="equipment.created";entityType="equipment";entityId=String((result as Record<string,unknown>).equipment&&(result as Record<string,Record<string,unknown>>).equipment.id);
  } else {
    const equipmentService=path.match(/^\/equipment\/([^/]+)\/service-records$/)?.[1],serviceRecordId=path.match(/^\/service-records\/([^/]+)$/)?.[1];
    const brokerFileId=path.match(/^\/broker\/sales-files\/([^/]+)$/)?.[1],brokerAction=path.match(/^\/broker\/sales-files\/([^/]+)\/(document-status|address-verification|mandate|closing|release)$/);
    const customerActionId=path.match(/^\/customer-actions\/([^/]+)\/respond$/)?.[1],opportunityId=path.match(/^\/partner-opportunities\/([^/]+)\/complete$/)?.[1];
    if(method==="POST"&&equipmentService){
      const equipment=collection(snapshot,"equipmentRecords").find(x=>String(x.id)===equipmentService);if(!equipment)fail("Equipment nicht gefunden",404);if(!allowedProperties.has(equipment.propertyId))fail("Kein Zugriff",403);if(partner&&equipment.tradeId!==partner.primaryTradeId)fail("Fremdes Gewerk",403);
      result={id:identifier("service"),equipmentId:equipment.id,propertyId:equipment.propertyId,partnerId:partner?.id||body.partnerId||null,serviceDate:body.serviceDate||new Date().toISOString().slice(0,10),serviceType:clean(body.serviceType||body.type,120),notes:clean(body.notes,2000),status:"recorded",documents:[],createdAt:new Date().toISOString(),createdBy:sourceUserId};collection(snapshot,"partnerServiceRecords").unshift(result as Record<string,unknown>);action="service_record.created";entityType="service_record";entityId=String((result as Record<string,unknown>).id);
    } else if(method==="PATCH"&&serviceRecordId){
      const row=collection(snapshot,"partnerServiceRecords").find(x=>String(x.id)===serviceRecordId);if(!row)fail("Serviceeintrag nicht gefunden",404);if(!allowedProperties.has(row.propertyId))fail("Kein Zugriff",403);for(const key of ["serviceDate","serviceType","notes","status"])if(key in body)row[key]=clean(body[key],key==="notes"?2000:160);row.updatedAt=new Date().toISOString();result=row;action="service_record.updated";entityType="service_record";entityId=serviceRecordId;
    } else if((method==="PATCH"||method==="POST")&&(brokerFileId||brokerAction)){
      if(!admin&&profile.role!=="broker_partner")fail("Keine Berechtigung",403);const id=brokerFileId||brokerAction![1],row=collection(snapshot,"salesFiles").find(x=>String(x.id)===id);if(!row)fail("Verkaufsakte nicht gefunden",404);if(!allowedProperties.has(row.propertyId))fail("Kein Zugriff",403);
      const step=brokerAction?.[2]||"update";
      if(step==="document-status"){const statuses=typeof row.documentStatuses==="object"&&row.documentStatuses?row.documentStatuses as Record<string,unknown>:{};const documentType=clean(body.documentType,120),status=clean(body.status,80);if(!documentType||!["external_requested","customer_requested","unavailable","not_required","available"].includes(status))fail("Dokumenttyp oder Status ungültig");statuses[documentType]={status,note:clean(body.note,500),updatedAt:new Date().toISOString(),updatedBy:sourceUserId};row.documentStatuses=statuses;}
      else if(step==="address-verification"){row.addressVerification={verified:Boolean(body.verified??body.addressConfirmed),note:clean(body.note,500),updatedAt:new Date().toISOString(),updatedBy:sourceUserId};}
      else if(step==="mandate"){const mandate={id:identifier("mandate"),salesFileId:id,propertyId:row.propertyId,partnerId:partner?.id||body.partnerId||row.partnerId||null,commissionModel:clean(body.commissionModel,80),commissionPercent:Number(body.commissionPercent||0),contractStart:body.contractStart||null,contractEnd:body.contractEnd||null,transmittedAt:new Date().toISOString(),status:"transmitted"};collection(snapshot,"brokerMandates").unshift(mandate);row.mandateId=mandate.id;result=mandate;}
      else if(step==="closing"){const closing={id:identifier("closing"),salesFileId:id,propertyId:row.propertyId,partnerId:partner?.id||row.partnerId||null,notarizationDate:body.notarizationDate||null,salePrice:Number(body.salePrice||row.askingPrice||0),recordedAt:new Date().toISOString()};if(!closing.notarizationDate)fail("Beurkundungsdatum ist erforderlich");collection(snapshot,"brokerClosings").unshift(closing);row.status="completed";result=closing;}
      else if(step==="release"){const required=["propertyId","calculatedValue"];if(required.some(k=>!row[k])||Number(row.completeness||0)<100)fail("Verkaufsakte ist noch nicht vollständig");row.status="ready";row.releasedAt=new Date().toISOString();row.locked=true;}
      else {const protectedKeys=new Set(["id","propertyId","partnerId"]);for(const [k,v] of Object.entries(body))if(!protectedKeys.has(k))row[k]=typeof v==="string"?clean(v,2000):v;row.updatedAt=new Date().toISOString();}
      result=result||row;action=`broker.sales_file.${step}`;entityType="sales_file";entityId=id;
    } else if(method==="POST"&&customerActionId){
      const row=collection(snapshot,"customerActions").find(x=>String(x.id)===customerActionId);if(!row)fail("Kundenaktion nicht gefunden",404);if(!allowedProperties.has(row.propertyId))fail("Kein Zugriff",403);row.response=clean(body.response,80);row.respondedAt=new Date().toISOString();row.status="responded";result=row;action="customer_action.responded";entityType="customer_action";entityId=customerActionId;
    } else if(method==="POST"&&opportunityId){
      const row=collection(snapshot,"partnerOpportunities").find(x=>String(x.id)===opportunityId);if(!row)fail("Opportunity nicht gefunden",404);if(!admin&&row.partnerId!==partner?.id)fail("Kein Zugriff",403);row.status="completed";row.completedAt=new Date().toISOString();row.completionNote=clean(body.note,1000);result=row;action="opportunity.completed";entityType="partner_opportunity";entityId=opportunityId;
    } else {
    const caseId=path.match(/^\/cases\/([^/]+)$/)?.[1],partnerId=path.match(/^\/partners\/([^/]+)$/)?.[1],equipmentId=path.match(/^\/equipment\/([^/]+)$/)?.[1];
    const key=caseId?"serviceCases":partnerId?"partners":equipmentId?"equipmentRecords":"",id=caseId||partnerId||equipmentId;
    if(!key||!id)return undefined;const rows=collection(snapshot,key),row=rows.find(x=>String(x.id)===id);if(!row)fail("Datensatz nicht gefunden",404);
    if(partnerId&&!admin)fail("Keine Berechtigung",403);if((caseId||equipmentId)&&!allowedProperties.has(row.propertyId))fail("Kein Zugriff",403);
    if(method==="DELETE"){if(profile.role!=="super_admin")fail("Keine Berechtigung",403);snapshot.state[key]=rows.filter(x=>x!==row);result={deleted:true,id};action=`${entityType||key}.deleted`;}
    else if(method==="PATCH"&&equipmentId){
      if(!partner)fail("Fachliche Spezifikationen dürfen nur vom zugeordneten Gewerkepartner gepflegt werden",403);if(row.tradeId!==partner.primaryTradeId)fail("Kein Schreibzugriff auf dieses Equipment",403);
      const previous={...((row.specifications as Record<string,unknown>)||{})},normalized=normalizeEquipmentFields(String(row.tradeId),body,row),verify=body.verify===true||body.verify==="true";
      if(normalized.errors.length)fail("Mindestens eine Fachangabe ist ungültig");if(verify&&!normalized.quality.requiredComplete)throw Object.assign(new Error("Fachliche Verifizierung erst nach vollständigen Pflichtangaben möglich"),{status:422,missingRequired:normalized.missingRequired});
      const firstConfiguration=!row.updatedAt&&!Object.values(previous).some(value=>value!==null&&value!==""&&value!==undefined),now=new Date().toISOString();row.specifications=normalized.values;row.dataQuality=normalized.quality;row.updatedAt=now;row.updatedBy=sourceUserId;
      for(const [legacy,currentId] of Object.entries({label:"instance_label",year:"year_of_construction",lastMaintenance:"last_maintenance_date",lastModernization:"last_renovation_date"}))if(currentId in normalized.values)row[legacy]=normalized.values[currentId];
      row.verification={...((row.verification as Record<string,unknown>)||{}),status:verify?"verified":"partial",verifiedAt:verify?now:null,verifiedBy:verify?sourceUserId:null,source:"licensed_partner",fieldCount:Object.values(normalized.values).filter(v=>v!==null&&v!==""&&v!==undefined).length,requiredCount:normalized.schema.requiredCount};
      const customer=collection(snapshot,"customers").find(x=>x.id===collection(snapshot,"properties").find(p=>p.id===row.propertyId)?.customerId),notification={id:identifier("notification"),userId:customer?.id||null,type:firstConfiguration?"equipment.configured":"equipment.updated",title:firstConfiguration?"Ihre Gewerkakte wurde eingerichtet":"Ihre Gewerkakte wurde aktualisiert",message:`Der Fachpartner ${partner.company} hat die technischen Daten für ${row.label||row.tradeId} ${firstConfiguration?"erstmalig erfasst":"geändert"}.`,propertyId:row.propertyId,equipmentId:row.id,partnerId:partner.id,createdAt:now,status:"queued",channel:"app_push"};collection(snapshot,"notifications").unshift(notification);result={equipment:row,notification:{id:notification.id,status:notification.status,channel:notification.channel},nextStep:{code:"service_record",title:"Nächster Schritt: Serviceheft pflegen",message:"Dokumentieren Sie künftig jede Prüfung, Wartung oder Reparatur mit Datum, Ergebnis und vorhandenen Nachweisen im Serviceheft."}};action=firstConfiguration?"equipment.specification.created":"equipment.specification.updated";
    }
    else if(method==="PATCH"){const protectedKeys=new Set(["id","userId","propertyId","password","passwordHash"]);for(const [k,v] of Object.entries(body))if(!protectedKeys.has(k))row[k]=typeof v==="string"?clean(v,2000):v;row.updatedAt=new Date().toISOString();result=row;action=`${key}.updated`;}
    else return undefined;entityType=key;entityId=id;
    }
  }
  await replaceRuntime(service,snapshot,profile.id,action,entityType,entityId,{sourceUserId});
  if(method==="PATCH"&&path==="/account")await service.from("portal_users").update({display_name:clean(body.name||profile.display_name,120),updated_at:new Date().toISOString()}).eq("id",profile.id);
  if(mailAfterCommit){const delivery=await sendPortalMail(mailAfterCommit.channel,mailAfterCommit.recipientEmail,mailAfterCommit.subject,mailAfterCommit.message);if(result&&typeof result==="object"){const target=(result as Record<string,unknown>).mail;if(target&&typeof target==="object")Object.assign(target,delivery,{from:(delivery as Record<string,unknown>).sender||mailAfterCommit.channel});else Object.assign(result as Record<string,unknown>,{delivery,...delivery});}}
  return {status:method==="POST"?201:200,body:result};
}
